POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "DevIA",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/babcdec7-cde0-4c8c-b549-5b15214eed54/attendees
Content-Type: application/json

{
  "name": "Samuel Oliveira",
  "email": "samuelloliiveira2@gmail.com"
}

###

GET http://localhost:3333/events/babcdec7-cde0-4c8c-b549-5b15214eed54

###

GET http://localhost:3333/attendees/5/badge

###

GET http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/babcdec7-cde0-4c8c-b549-5b15214eed54/attendees?query=samuel